apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: tap-config-accelerator
spec:
  git:
    url: https://github.com/ndwinton/tap-config-accelerator
    ref:
      branch: main
